### ISSUE TITLE
[Bug]: panic when port is in use

### ISSUE THREAD

**Issue by rogpeppe** [project-zot/zot#1392]
### zot version

9cc990d7ca7f5e703fdd54083ca458c77ee8e47d

### Describe the bug

zot panics when the port is already in use. This should be a normal failure, not a panic.

### To reproduce

First run some other server on port 5000 (e.g. `docker run -p5000:5000 registry`).

Then, in the `examples` directory:

```
% zot serve config-minimal.json
{"level":"info","time":"2023-04-27T16:36:18+01:00","message":"HTTP port 5000\n"}
{"level":"info","params":{"distSpecVersion":"1.1.0-dev","GoVersion":"devel","Commit":"v2.0.0-rc3-64-g9cc990d-dirty","ReleaseTag":"v2.0.0-rc3","BinaryType":"-sync-search-scrub-metrics-lint-ui-mgmt-userprefs","Storage":{"RootDirectory":"/tmp/zot","Dedupe":true,"RemoteCache":false,"GC":true,"Commit":false,"GCDelay":3600000000000,"GCInterval":0,"StorageDriver":null,"CacheDriver":null,"SubPaths":null},"HTTP":{"Address":"127.0.0.1","Port":"5000","AllowOrigin":"","TLS":null,"Auth":{"FailDelay":0,"HTPasswd":{"Path":""},"LDAP":null,"Bearer":null},"AccessControl":null,"Realm":"","Ratelimit":null},"Log":{"Level":"debug","Output":"","Audit":""},"Extensions":null},"goroutine":1,"caller":"zotregistry.io/zot/pkg/api/controller.go:236","time":"2023-04-27T16:36:18.109559577+01:00","message":"configuration settings"}
{"level":"info","cpus":8,"max. open files":1048576,"listen backlog":"4096","max. inotify watches":"65536","goroutine":1,"caller":"zotregistry.io/zot/pkg/api/controller.go:111","time":"2023-04-27T16:36:18.109620887+01:00","message":"runtime params"}
{"level":"debug","component":"scheduler","goroutine":51,"caller":"zotregistry.io/zot/pkg/scheduler/scheduler.go:134","time":"2023-04-27T16:36:18.111773859+01:00","message":"scheduler: pushing task into worker pool"}
{"level":"debug","component":"scheduler","goroutine":51,"caller":"zotregistry.io/zot/pkg/scheduler/scheduler.go:134","time":"2023-04-27T16:36:18.112155637+01:00","message":"scheduler: pushing task into worker pool"}
{"level":"warn","goroutine":1,"caller":"zotregistry.io/zot/pkg/debug/swagger/swagger_disabled.go:23","time":"2023-04-27T16:36:18.112307837+01:00","message":"skipping enabling swagger because given zot binary doesn't include this feature, please build a binary that does so"}
{"level":"debug","component":"scheduler","goroutine":51,"caller":"zotregistry.io/zot/pkg/scheduler/scheduler.go:134","time":"2023-04-27T16:36:18.112473162+01:00","message":"scheduler: pushing task into worker pool"}
{"level":"debug","component":"scheduler","worker":1,"goroutine":38,"caller":"zotregistry.io/zot/pkg/scheduler/scheduler.go:99","time":"2023-04-27T16:36:18.112502338+01:00","message":"scheduler: starting task"}
{"level":"info","digest":"sha256:66d65d5468847c7ba56500a93aaf616e2151f33ec799917288c1d804d96b0c74","goroutine":38,"caller":"zotregistry.io/zot/pkg/storage/local/local.go:1831","time":"2023-04-27T16:36:18.112567617+01:00","caller":"zotregistry.io/zot/pkg/storage/local/local.go:1831","message":"rebuild dedupe: deduping blobs for digest"}
panic: listen tcp 127.0.0.1:5000: bind: address already in use

goroutine 1 [running]:
zotregistry.io/zot/pkg/cli.newServeCmd.func1(0xc00139e300?, {0xc000ee66d0, 0x1, 0x1?})
	zotregistry.io/zot/pkg/cli/root.go:71 +0xdb
github.com/spf13/cobra.(*Command).execute(0xc00139e300, {0xc000ee6690, 0x1, 0x1})
	github.com/spf13/cobra@v1.7.0/command.go:944 +0x7e7
github.com/spf13/cobra.(*Command).ExecuteC(0xc00139e000)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3ac
github.com/spf13/cobra.(*Command).Execute(0xc0000061a0?)
	github.com/spf13/cobra@v1.7.0/command.go:992 +0x13
main.main()
	zotregistry.io/zot/cmd/zot/main.go:10 +0x18
```

### Expected behavior

Exit code 1. No panic.

**Comment by rchincha** [comment]
There are others under pkg/cli which we should clean as well and replace with a non-zero os.Exit()
