### ISSUE TITLE
[Bug]: Crash while starting

### ISSUE THREAD

**Issue by Jean-Daniel** [project-zot/zot#2146]
### zot version

v2.0.0

### Describe the bug

```
{"level":"info","cpus":32,"max. open files":1048576,"listen backlog":"4096","max. inotify watches":"1001060","goroutine":1,"caller":"zotregistry.io/zot/pkg/api/controller.go:90","time":"2023-12-20T11:24:18.070913587Z","message":"runtime params"}
{"level":"info","component":"metadb","goroutine":1,"caller":"zotregistry.io/zot/pkg/meta/parse.go:28","time":"2023-12-20T11:24:18.07262561Z","message":"parsing storage and initializing"}
{"level":"info","signal":15,"goroutine":79,"caller":"zotregistry.io/zot/pkg/cli/server/config_reloader.go:40","time":"2023-12-20T11:24:45.889166478Z","message":"received signal"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x108 pc=0x5649114c8d09]

goroutine 79 [running]:
zotregistry.io/zot/pkg/scheduler.(*Scheduler).Shutdown(0xc003140ea0?)
	zotregistry.io/zot/pkg/scheduler/scheduler.go:219 +0x29
zotregistry.io/zot/pkg/api.(*Controller).StopBackgroundTasks(...)
	zotregistry.io/zot/pkg/api/controller.go:379
zotregistry.io/zot/pkg/api.(*Controller).Shutdown(0xc0010cd8c0)
	zotregistry.io/zot/pkg/api/controller.go:372 +0x28
zotregistry.io/zot/pkg/cli/server.signalHandler(0xc0010cd8c0, 0x0?)
	zotregistry.io/zot/pkg/cli/server/config_reloader.go:43 +0xb4
created by zotregistry.io/zot/pkg/cli/server.initShutDownRoutine
	zotregistry.io/zot/pkg/cli/server/config_reloader.go:52 +0x8a
```

Configuration: 

```json
{
    "level": "info", 
    "params": {
        "distSpecVersion": "1.1.0-dev", 
        "GoVersion": "go1.20.12", 
        "Commit": "v2.0.0-c2196e3ae1625b87b9bdd3ed002466b71c51fc20", 
        "ReleaseTag": "v2.0.0", 
        "BinaryType": "-imagetrust-lint-metrics-mgmt-profile-scrub-search-sync-ui-userprefs", 
        "Storage": {
            "RootDirectory": "/tmp/zot", 
            "Dedupe": false, 
            "RemoteCache": false, 
            "GC": false, 
            "Commit": false, 
            "GCDelay": 0, 
            "GCInterval": 0, 
            "Retention": {
                "DryRun": false, 
                "Delay": 0, 
                "Policies": null
            }, 
            "StorageDriver": {
                "accesskey": "-", 
                "bucket": "registry", 
                "endpoint": "-", 
                "name": "s3", 
                "region": "-", 
                "regionendpoint": "-", 
                "rootdirectory": "/storage", 
                "secretkey": "-", 
                "secure": false
            }, 
            "CacheDriver": null, 
            "SubPaths": null
        }, 
        "HTTP": {
            "Address": "0.0.0.0", 
            "ExternalURL": "", 
            "Port": "5000", 
            "AllowOrigin": "", 
            "TLS": {
                "Cert": "/secrets/tls/tls.crt", 
                "Key": "/secrets/tls/tls.key", 
                "CACert": ""
            }, 
            "Auth": {
                "FailDelay": 0, 
                "HTPasswd": {
                    "Path": "/secrets/htpasswd"
                }, 
                "LDAP": null, 
                "Bearer": null, 
                "OpenID": null, 
                "APIKey": false
            }, 
            "AccessControl": {
                "repositories": {
                    "**": {
                        "Policies": null, 
                        "DefaultPolicy": null, 
                        "AnonymousPolicy": [
                            "read"
                        ]
                    }
                }, 
                "AdminPolicy": {
                    "Users": null, 
                    "Actions": null, 
                    "Groups": null
                }, 
                "Groups": null, 
                "Metrics": {
                    "Users": null
                }
            }, 
            "Realm": "", 
            "Ratelimit": null
        }, 
        "Log": {
            "Level": "info", 
            "Output": "", 
            "Audit": ""
        }, 
        "Extensions": {
            "Search": {
                "Enable": false, 
                "CVE": null
            }, 
            "Sync": null, 
            "Metrics": {
                "Enable": false, 
                "Prometheus": {
                    "Path": "/metrics"
                }
            }, 
            "Scrub": null, 
            "Lint": null, 
            "UI": {
                "Enable": false
            }, 
            "Mgmt": null, 
            "APIKey": null, 
            "Trust": null
        }, 
        "scheduler": null
    }, 
    "goroutine": 1, 
    "caller": "zotregistry.io/zot/pkg/api/controller.go:221", 
    "time": "2023-12-20T11:24:18.07063515Z", 
    "message": "configuration settings"
}
```

### To reproduce

1. Configuration
2. Client tool used
3. Seen error

**Comment by peusebiu** [comment]
Hello @Jean-Daniel  thanks for the feedback, one question, this happens when you stop zot, right? ctlr+c?

**Comment by Jean-Daniel** [comment]
It appends while starting zot. It loads the config, start to scan the repository and crashes.

It never starts serving requests. Sometimes, before crashing, it manages to log a couple of other lines indicating which repository it starts scanning, but nothing more.
