### ISSUE TITLE
ci/cd: failure in unit test

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#355]
**Describe the bug**

https://github.com/project-zot/zot/runs/4731644623?check_suite_focus=true

```
{"Level":"debug","Output":"","Audit":""},"Extensions":null},"goroutine":199,"caller":"zotregistry.io/zot/pkg/api/controller.go:80","time":"2022-01-06T20:37:49.833280772Z","message":"configuration settings"}
panic: listen tcp 127.0.0.1:39873: bind: address already in use

goroutine 199 [running]:
zotregistry.io/zot/pkg/exporter/api_test.TestNewExporter.func1.1.3.1(0xc001ba7600)
	zotregistry.io/zot/pkg/exporter/api_test/controller_test.go:140 +0xeb
created by zotregistry.io/zot/pkg/exporter/api_test.TestNewExporter.func1.1.3
	zotregistry.io/zot/pkg/exporter/api_test/controller_test.go:137 +0x3c5
FAIL	zotregistry.io/zot/pkg/exporter/api	3.571s
?   	zotregistry.io/zot/pkg/exporter/cli	[no test files]
?   	zotregistry.io/zot/pkg/extensions	[no test files]
?   	zotregistry.io/zot/pkg/extensions/config	[no test files]
?   	zotregistry.io/zot/pkg/extensions/monitoring	[no test files]
?   	zotregistry.io/zot/pkg/extensions/search	[no test files]
?   	zotregistry.io/zot/pkg/extensions/search/common	[no test files]
?   	zotregistry.io/zot/pkg/extensions/search/cve	[no test files]
?   	zotregistry.io/zot/pkg/extensions/search/digest	[no test files]
```

**Comment by adodon2go** [comment]
Issue does not reproduce with latest builds.
