### ISSUE TITLE
bug metrics: zot crashes after a while 

### ISSUE THREAD

**Issue by adodon2go** [project-zot/zot#358]
**Describe the bug**
Affects zot minimal with node-exporter. After a while zot crashes with fatal message:
fatal error: concurrent map iteration and map write

goroutine 2828366 [running]:
runtime.throw({0x11d5fd4, 0x7f22179591d8})
	runtime/panic.go:1198 +0x71 fp=0xc00129ec98 sp=0xc00129ec68 pc=0x434631
runtime.mapiternext(0x50)
	runtime/map.go:858 +0x4eb fp=0xc00129ed08 sp=0xc00129ec98 pc=0x40f8eb
reflect.mapiternext(0x4)
	runtime/map.go:1346 +0x19 fp=0xc00129ed20 sp=0xc00129ed08 pc=0x45e639
github.com/modern-go/reflect2.(*UnsafeMapIterator).UnsafeNext(0x1099440)
	github.com/modern-go/reflect2@v1.0.2/unsafe_map.go:128 +0x32 fp=0xc00129ed48 sp=0xc00129ed20 pc=0xdf45d2
github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc000541b00, 0xc0015835e0, 0xc001d70960)
	github.com/json-iterator/go@v1.1.12/reflect_map.go:297 +0x31a fp=0xc00129eeb8 sp=0xc00129ed48 pc=0xe388da
github.com/json-iterator/go.(*placeholderEncoder).Encode(0x104b680, 0xc00129ef01, 0xc001d70978)
	github.com/json-iterator/go@v1.1.12/reflect.go:332 +0x22 fp=0xc00129eee0 sp=0xc00129eeb8 pc=0xe314e2
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc0005460f0, 0xf38fba, 0xc001d70960)
	github.com/json-iterator/go@v1.1.12/reflect_struct_encoder.go:110 +0x56 fp=0xc00129ef58 sp=0xc00129eee0 pc=0xe46016
github.com/json-iterator/go.(*structEncoder).Encode(0xc0005461e0, 0xf119, 0xc001d70960)
	github.com/json-iterator/go@v1.1.12/reflect_struct_encoder.go:158 +0x765 fp=0xc00129f040 sp=0xc00129ef58 pc=0xe46a25
github.com/json-iterator/go.(*OptionalEncoder).Encode(0x4, 0xc00129f0e8, 0x7030f3)
	github.com/json-iterator/go@v1.1.12/reflect_optional.go:70 +0xa4 fp=0xc00129f090 sp=0xc00129f040 pc=0xe3db44
github.com/json-iterator/go.(*sliceEncoder).Encode(0xc00000c870, 0xc00002c228, 0xc001d70960)
	github.com/json-iterator/go@v1.1.12/reflect_slice.go:42 +0x302 fp=0xc00129f148 sp=0xc00129f090 pc=0xe3e5e2
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc0005462d0, 0xf40bd2, 0xc001d70960)
	github.com/json-iterator/go@v1.1.12/reflect_struct_encoder.go:110 +0x56 fp=0xc00129f1c0 sp=0xc00129f148 pc=0xe46016
github.com/json-iterator/go.(*structEncoder).Encode(0xc000546330, 0x0, 0xc001d70960)
	github.com/json-iterator/go@v1.1.12/reflect_struct_encoder.go:158 +0x765 fp=0xc00129f2a8 sp=0xc00129f1c0 pc=0xe46a25
github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc00129f320, 0x40ae85, 0x105f460)
	github.com/json-iterator/go@v1.1.12/reflect_optional.go:70 +0xa4 fp=0xc00129f2f8 sp=0xc00129f2a8 pc=0xe3db44
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc0004cf980, 0xc00002c1e0, 0xc00129f370)
	github.com/json-iterator/go@v1.1.12/reflect.go:219 +0x82 fp=0xc00129f330 sp=0xc00129f2f8 pc=0xe30aa2
github.com/json-iterator/go.(*Stream).WriteVal(0xc001d70960, {0xfb0760, 0xc00002c1e0})
	github.com/json-iterator/go@v1.1.12/reflect.go:98 +0x158 fp=0xc00129f3a0 sp=0xc00129f330 pc=0xe2fd98
github.com/json-iterator/go.(*frozenConfig).Marshal(0xc00030c1e0, {0xfb0760, 0xc00002c1e0})
	github.com/json-iterator/go@v1.1.12/config.go:299 +0xc9 fp=0xc00129f438 sp=0xc00129f3a0 pc=0xe26f49
zotregistry.io/zot/pkg/api.WriteJSON({0x1480ad0, 0xc0015214c0}, 0x1491f78, {0xfb0760, 0xc00002c1e0})
	zotregistry.io/zot/pkg/api/routes.go:1281 +0x4e fp=0xc00129f490 sp=0xc00129f438 pc=0xf2d4ce
zotregistry.io/zot/pkg/api.(*RouteHandler).GetMetrics(0x46e81e, {0x1480ad0, 0xc0015214c0}, 0x0)
	zotregistry.io/zot/pkg/api/routes.go:1252 +0x4f fp=0xc00129f4c8 sp=0xc00129f490 pc=0xf2d2af
zotregistry.io/zot/pkg/api.(*RouteHandler).GetMetrics-fm({0x1480ad0, 0xc0015214c0}, 0xc001b4c250)
	zotregistry.io/zot/pkg/api/routes.go:1250 +0x3c fp=0xc00129f4f8 sp=0xc00129f4c8 pc=0xf3091c
net/http.HandlerFunc.ServeHTTP(0x0, {0x1480ad0, 0xc0015214c0}, 0x0)
	net/http/server.go:2047 +0x2f fp=0xc00129f520 sp=0xc00129f4f8 pc=0x6fde6f
zotregistry.io/zot/pkg/api.basicAuthHandler.func1.1({0x1480ad0, 0xc0015214c0}, 0x500000002)
	zotregistry.io/zot/pkg/api/authn.go:106 +0x104 fp=0xc00129f558 sp=0xc00129f520 pc=0xf19c24
net/http.HandlerFunc.ServeHTTP(0x203000, {0x1480ad0, 0xc0015214c0}, 0x25e1d40)
	net/http/server.go:2047 +0x2f fp=0xc00129f580 sp=0xc00129f558 pc=0x6fde6f
github.com/gorilla/handlers.recoveryHandler.ServeHTTP({{0x146f480, 0xc001900ae0}, {0x146fb40, 0xc00002c180}, 0x0}, {0x1480ad0, 0xc0015214c0}, 0x466733)
	github.com/gorilla/handlers@v1.5.1/recovery.go:78 +0xeb fp=0xc00129f600 sp=0xc00129f580 pc=0xbae54b
github.com/gorilla/handlers.(*recoveryHandler).ServeHTTP(0xc001900b10, {0x1480ad0, 0xc0015214c0}, 0x0)
	<autogenerated>:1 +0x8f fp=0xc00129f678 sp=0xc00129f600 pc=0xbaeacf
zotregistry.io/zot/pkg/api.SessionLogger.func1.1({0x1480a40, 0xc00190a000}, 0xc00156ef00)
	zotregistry.io/zot/pkg/api/session.go:51 +0x13a fp=0xc00129f8d0 sp=0xc00129f678 pc=0xf2ed7a
net/http.HandlerFunc.ServeHTTP(0x10f0e60, {0x1480a40, 0xc00190a000}, 0x1c)
	net/http/server.go:2047 +0x2f fp=0xc00129f8f8 sp=0xc00129f8d0 pc=0x6fde6f
zotregistry.io/zot/pkg/api.DefaultHeaders.func1.1({0x1480a40, 0xc00190a000}, 0xc001900ba0)
	zotregistry.io/zot/pkg/api/controller.go:66 +0x19b fp=0xc00129f970 sp=0xc00129f8f8 pc=0xf2febb
net/http.HandlerFunc.ServeHTTP(0xc00156ee00, {0x1480a40, 0xc00190a000}, 0xc00129f9f8)
	net/http/server.go:2047 +0x2f fp=0xc00129f998 sp=0xc00129f970 pc=0x6fde6f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001fc180, {0x1480a40, 0xc00190a000}, 0xc00156ed00)
	github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf fp=0xc00129fac0 sp=0xc00129f998 pc=0x851c2f
net/http.serverHandler.ServeHTTP({0xc001b423c0}, {0x1480a40, 0xc00190a000}, 0xc00156ed00)
	net/http/server.go:2879 +0x43b fp=0xc00129fb80 sp=0xc00129fac0 pc=0x7013db
net/http.(*conn).serve(0xc0019974a0, {0x1489a60, 0xc0000cd9e0})
	net/http/server.go:1930 +0xb08 fp=0xc00129ffb8 sp=0xc00129fb80 pc=0x6fcf48
net/http.(*Server).Serve·dwrap·87()
	net/http/server.go:3034 +0x2e fp=0xc00129ffe0 sp=0xc00129ffb8 pc=0x701d2e
runtime.goexit()
	runtime/asm_amd64.s:1581 +0x1 fp=0xc00129ffe8 sp=0xc00129ffe0 pc=0x464021
created by net/http.(*Server).Serve
	net/http/server.go:3034 +0x4e8

goroutine 1 [runnable]:
syscall.Syscall6(0x120, 0xa, 0xc00129d680, 0xc00129d66c, 0x80800, 0x0, 0x0)
	syscall/asm_linux_amd64.s:43 +0x5
syscall.accept4(0xc00129d680, 0x7f21f0a2e868, 0xc00129d680, 0x41768d)
	syscall/zsyscall_linux_amd64.go:1405 +0x4e
syscall.Accept4(0xc00129d738, 0x45ef09)
	syscall/syscall_linux.go:575 +0x6d
internal/poll.accept(0xc000099e80)
	internal/poll/sock_cloexec.go:18 +0x2e
internal/poll.(*FD).Accept(0xc000099e80)
	internal/poll/fd_unix.go:393 +0x1be
net.(*netFD).accept(0xc000099e80)
	net/fd_unix.go:173 +0x35
net.(*TCPListener).accept(0xc000135788)
	net/tcpsock_posix.go:140 +0x28
net.(*TCPListener).Accept(0xc000135788)
	net/tcpsock.go:262 +0x3d
net/http.(*Server).Serve(0xc000188380, {0x1480830, 0xc000135788})
	net/http/server.go:3002 +0x394
zotregistry.io/zot/pkg/api.(*Controller).Run(0xc00015f6b0)
	zotregistry.io/zot/pkg/api/controller.go:156 +0xb55
zotregistry.io/zot/pkg/cli.newServeCmd.func1(0xc0001b2000, {0xc000213080, 0x1, 0x1})
	zotregistry.io/zot/pkg/cli/root.go:79 +0x16f
github.com/spf13/cobra.(*Command).execute(0xc0001b2000, {0xc000213040, 0x1, 0x1})
	github.com/spf13/cobra@v1.2.1/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc00013d900)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	zotregistry.io/zot/cmd/zot/main.go:10 +0x1e

goroutine 9 [syscall, 36 minutes]:
syscall.Syscall6(0xe8, 0x7, 0xc00063fbec, 0x7, 0xffffffffffffffff, 0x0, 0x0)
	syscall/asm_linux_amd64.s:43 +0x5
golang.org/x/sys/unix.EpollWait(0x0, {0xc00063fbec, 0x0, 0x0}, 0x0)
	golang.org/x/sys@v0.0.0-20211110154304-99a53858aa08/unix/zsyscall_linux_amd64.go:56 +0x58
github.com/fsnotify/fsnotify.(*fdPoller).wait(0xc000446ac0)
	github.com/fsnotify/fsnotify@v1.5.1/inotify_poller.go:87 +0x7d
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc000456af0)
	github.com/fsnotify/fsnotify@v1.5.1/inotify.go:193 +0x2b0
created by github.com/fsnotify/fsnotify.NewWatcher
	github.com/fsnotify/fsnotify@v1.5.1/inotify.go:60 +0x1c7

goroutine 10 [chan receive, 36 minutes]:
zotregistry.io/zot/pkg/cli.newServeCmd.func1.1()
	zotregistry.io/zot/pkg/cli/root.go:76 +0x11e
created by zotregistry.io/zot/pkg/cli.newServeCmd.func1
	zotregistry.io/zot/pkg/cli/root.go:52 +0x165

goroutine 11 [select]:
zotregistry.io/zot/pkg/extensions/monitoring.(*metricServer).Run(0xc00029fb80)
	zotregistry.io/zot/pkg/extensions/monitoring/minimal.go:138 +0x11a
created by zotregistry.io/zot/pkg/extensions/monitoring.NewMetricsServer
	zotregistry.io/zot/pkg/extensions/monitoring/minimal.go:202 +0x505

goroutine 12 [sleep]:
time.Sleep(0x6fc23ac00)
	runtime/time.go:193 +0x12e
zotregistry.io/zot/pkg/extensions/monitoring.(*metricServer).Run.func1()
	zotregistry.io/zot/pkg/extensions/monitoring/minimal.go:132 +0x2c
created by zotregistry.io/zot/pkg/extensions/monitoring.(*metricServer).Run
	zotregistry.io/zot/pkg/extensions/monitoring/minimal.go:129 +0x8f

goroutine 22 [select, 36 minutes]:
zotregistry.io/zot/pkg/cli.newServeCmd.func1.1.1()
	zotregistry.io/zot/pkg/cli/root.go:55 +0xde
created by zotregistry.io/zot/pkg/cli.newServeCmd.func1.1
	zotregistry.io/zot/pkg/cli/root.go:53 +0xe9

goroutine 2976939 [runnable]:
internal/poll.runtime_pollWait(0x7f21f0b3adb0, 0x72)
	runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc000449400, 0xc001a50000, 0x0)
	internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000449400, {0xc001a50000, 0x8000, 0x8000})
	internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000449400, {0xc001a50000, 0xc001686da0, 0x45f97b})
	net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc00051e558, {0xc001a50000, 0x1, 0xc001a2c368})
	net/net.go:183 +0x45
net/http.(*connReader).Read(0xc001a2c360, {0xc001a50000, 0x8000, 0x8000})
	net/http/server.go:780 +0x16d
bufio.(*Reader).Read(0xc001d90480, {0xc001a50000, 0x8000, 0xc001a50000})
	bufio/bufio.go:213 +0x106
io.(*LimitedReader).Read(0xc001be6720, {0xc001a50000, 0xc001686e90, 0xc001686f18})
	io/io.go:473 +0x45
net/http.(*body).readLocked(0xc001a16940, {0xc001a50000, 0x8000, 0x8000})
	net/http/transfer.go:843 +0x3c
net/http.(*body).Read(0xc00069b3c0, {0xc001a50000, 0xc00069b3c0, 0xc00069b3c0})
	net/http/transfer.go:835 +0x125
io.copyBuffer({0x146f940, 0xc00069b3c0}, {0x7f21f0aa0b98, 0xc001a16940}, {0x0, 0x0, 0x0})
	io/io.go:423 +0x1b2
io.Copy(...)
	io/io.go:382
os.genericReadFrom(0x4a8535, {0x7f21f0aa0b98, 0xc001a16940})
	os/file.go:162 +0x5d
os.(*File).ReadFrom(0xc00051e560, {0x7f21f0aa0b98, 0xc001a16940})
	os/file.go:156 +0x1b0
io.copyBuffer({0x146db00, 0xc00051e560}, {0x7f21f0aa0b98, 0xc001a16940}, {0x0, 0x0, 0x0})
	io/io.go:409 +0x14b
io.Copy(...)
	io/io.go:382
zotregistry.io/zot/pkg/storage.(*ImageStoreFS).PutBlobChunkStreamed(0xc00029fcc0, {0xc0016bf8ba, 0x7}, {0xc0016bf8d0, 0x24}, {0x7f21f0aa0b98, 0xc001a16940})
	zotregistry.io/zot/pkg/storage/storage_fs.go:849 +0x1f6
zotregistry.io/zot/pkg/api.(*RouteHandler).PatchBlobUpload(0xc000128f70, {0x1480ad0, 0xc001a3a120}, 0xc001a22c00)
	zotregistry.io/zot/pkg/api/routes.go:934 +0x1bf
net/http.HandlerFunc.ServeHTTP(0x0, {0x1480ad0, 0xc001a3a120}, 0x0)
	net/http/server.go:2047 +0x2f
zotregistry.io/zot/pkg/api.basicAuthHandler.func1.1({0x1480ad0, 0xc001a3a120}, 0x500003e40)
	zotregistry.io/zot/pkg/api/authn.go:106 +0x104
net/http.HandlerFunc.ServeHTTP(0x203000, {0x1480ad0, 0xc001a3a120}, 0x25e1d40)
	net/http/server.go:2047 +0x2f
github.com/gorilla/handlers.recoveryHandler.ServeHTTP({{0x146f480, 0xc001a2c480}, {0x146fb40, 0xc00002c180}, 0x0}, {0x1480ad0, 0xc001a3a120}, 0x466733)
	github.com/gorilla/handlers@v1.5.1/recovery.go:78 +0xeb
zotregistry.io/zot/pkg/api.SessionLogger.func1.1({0x1480a40, 0xc001619ce0}, 0xc001a22c00)
	zotregistry.io/zot/pkg/api/session.go:51 +0x13a
net/http.HandlerFunc.ServeHTTP(0x10f0e60, {0x1480a40, 0xc001619ce0}, 0x1c)
	net/http/server.go:2047 +0x2f
zotregistry.io/zot/pkg/api.DefaultHeaders.func1.1({0x1480a40, 0xc001619ce0}, 0xc001a2c540)
	zotregistry.io/zot/pkg/api/controller.go:66 +0x19b
net/http.HandlerFunc.ServeHTTP(0xc001a22b00, {0x1480a40, 0xc001619ce0}, 0xc001e209f8)
	net/http/server.go:2047 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001fc180, {0x1480a40, 0xc001619ce0}, 0xc001a22a00)
	github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0x147db70}, {0x1480a40, 0xc001619ce0}, 0xc001a22a00)
	net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc00165b0e0, {0x1489a60, 0xc0000cd9e0})
	net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
	net/http/server.go:3034 +0x4e8

goroutine 2976733 [runnable]:
internal/poll.runtime_pollWait(0x7f21f0b2e660, 0x72)
	runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc001e10900, 0xc0015ec000, 0x0)
	internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc001e10900, {0xc0015ec000, 0x8000, 0x8000})
	internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc001e10900, {0xc0015ec000, 0xc0012a2da0, 0x45f97b})
	net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc001e16388, {0xc0015ec000, 0x1, 0xc0015aae18})
	net/net.go:183 +0x45
net/http.(*connReader).Read(0xc0015aae10, {0xc0015ec000, 0x8000, 0x8000})
	net/http/server.go:780 +0x16d
bufio.(*Reader).Read(0xc0007b8de0, {0xc0015ec000, 0x8000, 0xc0015ec000})
	bufio/bufio.go:213 +0x106
io.(*LimitedReader).Read(0xc00000cab0, {0xc0015ec000, 0xc0012a2e90, 0xc0012a2f18})
	io/io.go:473 +0x45
net/http.(*body).readLocked(0xc0018e7740, {0xc0015ec000, 0x8000, 0x8000})
	net/http/transfer.go:843 +0x3c
net/http.(*body).Read(0xc00073d4d0, {0xc0015ec000, 0xc00073d4d0, 0xc00073d4d0})
	net/http/transfer.go:835 +0x125
io.copyBuffer({0x146f940, 0xc00073d4d0}, {0x7f21f0aa0b98, 0xc0018e7740}, {0x0, 0x0, 0x0})
	io/io.go:423 +0x1b2
io.Copy(...)
	io/io.go:382
os.genericReadFrom(0x4a8535, {0x7f21f0aa0b98, 0xc0018e7740})
	os/file.go:162 +0x5d
os.(*File).ReadFrom(0xc001e16390, {0x7f21f0aa0b98, 0xc0018e7740})
	os/file.go:156 +0x1b0
io.copyBuffer({0x146db00, 0xc001e16390}, {0x7f21f0aa0b98, 0xc0018e7740}, {0x0, 0x0, 0x0})
	io/io.go:409 +0x14b
io.Copy(...)
	io/io.go:382
zotregistry.io/zot/pkg/storage.(*ImageStoreFS).PutBlobChunkStreamed(0xc00029fcc0, {0xc001993d6a, 0x7}, {0xc001993d80, 0x24}, {0x7f21f0aa0b98, 0xc0018e7740})
	zotregistry.io/zot/pkg/storage/storage_fs.go:849 +0x1f6
zotregistry.io/zot/pkg/api.(*RouteHandler).PatchBlobUpload(0xc000128f70, {0x1480ad0, 0xc001e156c0}, 0xc0015bab00)
	zotregistry.io/zot/pkg/api/routes.go:934 +0x1bf
net/http.HandlerFunc.ServeHTTP(0x0, {0x1480ad0, 0xc001e156c0}, 0x0)
	net/http/server.go:2047 +0x2f
zotregistry.io/zot/pkg/api.basicAuthHandler.func1.1({0x1480ad0, 0xc001e156c0}, 0x500003e40)
	zotregistry.io/zot/pkg/api/authn.go:106 +0x104
net/http.HandlerFunc.ServeHTTP(0x203000, {0x1480ad0, 0xc001e156c0}, 0x25e1d40)
	net/http/server.go:2047 +0x2f
github.com/gorilla/handlers.recoveryHandler.ServeHTTP({{0x146f480, 0xc0015aaf30}, {0x146fb40, 0xc00002c180}, 0x0}, {0x1480ad0, 0xc001e156c0}, 0x466733)
	github.com/gorilla/handlers@v1.5.1/recovery.go:78 +0xeb
zotregistry.io/zot/pkg/api.SessionLogger.func1.1({0x1480a40, 0xc0015d4000}, 0xc0015bab00)
	zotregistry.io/zot/pkg/api/session.go:51 +0x13a
net/http.HandlerFunc.ServeHTTP(0x10f0e60, {0x1480a40, 0xc0015d4000}, 0x1c)
	net/http/server.go:2047 +0x2f
zotregistry.io/zot/pkg/api.DefaultHeaders.func1.1({0x1480a40, 0xc0015d4000}, 0xc0015aaff0)
	zotregistry.io/zot/pkg/api/controller.go:66 +0x19b
net/http.HandlerFunc.ServeHTTP(0xc0015baa00, {0x1480a40, 0xc0015d4000}, 0xc0016f79f8)
	net/http/server.go:2047 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001fc180, {0x1480a40, 0xc0015d4000}, 0xc0015ba900)
	github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0x147db70}, {0x1480a40, 0xc0015d4000}, 0xc0015ba900)
	net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc001580d20, {0x1489a60, 0xc0000cd9e0})
	net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
	net/http/server.go:3034 +0x4e8

goroutine 2976940 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0xc001a16a90, 0x0)
	runtime/sema.go:513 +0x13d
sync.(*Cond).Wait(0xc00051e568)
	sync/cond.go:56 +0x8c
net/http.(*connReader).abortPendingRead(0xc001a2c6c0)
	net/http/server.go:720 +0xb5
net/http.(*response).finishRequest(0xc001619dc0)
	net/http/server.go:1611 +0x87
net/http.(*conn).serve(0xc00165b180, {0x1489a60, 0xc0000cd9e0})
	net/http/server.go:1935 +0xb3f
created by net/http.(*Server).Serve
	net/http/server.go:3034 +0x4e8

goroutine 2976942 [runnable]:
net.(*OpError).Timeout(0xc0018eae10)
	net/net.go:502 +0xa6
net/http.(*connReader).backgroundRead(0xc001a2c6c0)
	net/http/server.go:699 +0xa2
created by net/http.(*connReader).startBackgroundRead
	net/http/server.go:668 +0xcf

goroutine 2976887 [IO wait]:
internal/poll.runtime_pollWait(0x7f21f0b3c5d8, 0x72)
	runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc001e0b880, 0xc001b423d1, 0x0)
	internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc001e0b880, {0xc001b423d1, 0x1, 0x1})
	internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc001e0b880, {0xc001b423d1, 0x1059780, 0xc000066748})
	net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc001e16270, {0xc001b423d1, 0xc0018e41d0, 0xc001b2a550})
	net/net.go:183 +0x45
net/http.(*connReader).backgroundRead(0xc001b423c0)
	net/http/server.go:672 +0x3f
created by net/http.(*connReader).startBackgroundRead
	net/http/server.go:668 +0xcf

**To Reproduce**
1. I have a script that concurrently stresses a zot server (N clients that stresses during P period of time with images upload & download from zot)
2. Grafana configured to scrape metrics every 5 seconds from node exporter (probably the lower valuer the sooner issue reproduces)
2. After a while zot server crashes

**Expected behavior**
Zot server should not crash

**Comment by adodon2go** [comment]
Unable to reproduce this issue anymore.
